/**
 * Виды спорта, которые понимает прошивка.
 *
 * Перечень взят из заголовка iOS-SDK вендора (`UTEDeviceSportMode`), а не
 * выведен из наблюдений: устройство отдаёт только номера, и без этой таблицы
 * они остаются числами. Каталог конкретного браслета читается отдельно — он
 * заметно шире этого списка, и на неизвестные номера имя не выдумывается.
 */
export const SportType: Record<number, string> = {
  1: 'Running',
  2: 'Cycling',
  3: 'Rope Skipping',
  4: 'Swimming',
  5: 'Badminton',
  6: 'Table Tennis',
  7: 'Tennis',
  8: 'Mountaineering',
  9: 'Walking',
  10: 'Basketball',
  11: 'Soccer (USA)',
  12: 'Baseball',
  13: 'Volleyball',
  14: 'Cricket',
  15: 'Football (USA)',
  16: 'Hockey',
  17: 'Dance',
  18: 'Spinning Cycling',
  19: 'Yoga',
  20: 'Sit Ups',
  21: 'Treadmill',
  22: 'Gymnastics',
  23: 'Boating',
  24: 'Jumping Jacks',
  25: 'Free',
  26: 'Indoor Walking',
  27: 'Indoor Running',
  28: 'Strength Training',
  29: 'Stepping',
  30: 'Horse Riding',
  31: 'Elliptical Trainer',
  32: 'Tai Chi',
  33: 'Shuttlecock',
  34: 'Boxing',
  35: 'Outdoor Walking',
  36: 'Trail Running',
  37: 'Skiing',
  38: 'Ice Hockey',
  39: 'Taekwondo',
  40: 'VO2max Test',
  41: 'Rowing Machine',
  42: 'Walking Machine',
  43: 'Hiking',
  44: 'Athletics',
  45: 'Waist Training',
  46: 'Karate',
  47: 'Cool Down',
  48: 'Cross Training',
  49: 'Pilates',
  50: 'Cross Fit',
  51: 'Functional Training',
  52: 'Physical Training',
  53: 'Archery',
  54: 'Flexibility',
  55: 'Mixed Cardio',
  56: 'Latin Dance',
  57: 'Street Dance',
  58: 'Kickboxing',
  59: 'Barre',
  60: 'Australian Football',
  61: 'Martial Arts',
  62: 'Climb Stairs',
  63: 'Handball',
  64: 'Bowling',
  65: 'Squash',
  66: 'Curling',
  67: 'Hunting',
  68: 'Snowboarding',
  69: 'Leisure',
  70: 'American Football',
  71: 'Handcycling',
  72: 'Fishing',
  73: 'Frisbee',
  74: 'Rugby',
  75: 'Golf',
  76: 'Folk Dance',
  77: 'Downhill Skiing',
  78: 'Snow Sports',
  79: 'Meditation',
  80: 'Core Training',
  81: 'Skating',
  82: 'Fitness Game',
  83: 'Aerobics',
  84: 'Group Gymnastics',
  85: 'Kickboxing Gymnastics',
  86: 'Lacrosse',
  87: 'Foam Roller',
  88: 'Wrestling',
  89: 'Fencing',
  90: 'Softball',
  91: 'Horizontal Bar',
  92: 'Parallel Bars',
  93: 'Roller Skating',
  94: 'Hula Hoop',
  95: 'Darts',
  96: 'Pickleball',
  97: 'HIIT',
  98: 'Shoot',
  99: 'Judo',
  100: 'Trampoline',
  101: 'Skateboard',
  102: 'Hoverboard',
  103: 'Blading',
  104: 'Parkour',
  105: 'Diving',
  106: 'Surfing',
  107: 'Snorkeling',
  108: 'Pull ups',
  109: 'Push ups',
  110: 'Plank',
  111: 'Rock Climbing',
  112: 'High Jump',
  113: 'Bungee Jumping',
  114: 'Long Jump',
  115: 'Marathon',
};

/** Название вида спорта по номеру устройства. */
export function sportName(code: number): string {
  return SportType[code] ?? `Sport ${code}`;
}
